### ISSUE TITLE
Reset states after epoch?

### ISSUE THREAD

**Issue by jondo** [ahstat/deep-learning#1]
in [this Stackoverflow answer](https://stackoverflow.com/a/49666510/1389680), Astrid uses LSTM as shown here, but additionally resets states after epochs. As a newcomer in LSTM usage, I wonder: Would this also be useful for your example?

**Comment by ahstat** [comment]
She's doing right, it is better to reset states after each epoch.
Using CuDNNLSTM, GRU, and early stopping are also good moves.

I initially thought that states were reset automatically after each epoch, but it is not the case. See https://stackoverflow.com/questions/43882796/when-does-keras-reset-an-lstm-state/44183738#44183738 and https://github.com/karpathy/char-rnn/issues/78

For my specific example, improvement doing this additional reset would be close to 0.

I'll update this later this week

**Comment by ahstat** [comment]
Also, this code in linked with this blog post: https://ahstat.github.io/RNN-Keras-time-series/

**Comment by jondo** [comment]
Thanks for your answer!

Yes, I found both the blog post and this repo via [your original Stackoverflow answer](https://stackoverflow.com/a/48521460). I suggest to add the blog post link to either the repo description (after 'Learning deep learning') or a `README.md` file.

**Comment by ahstat** [comment]
thank you for your feedback
